version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_tinder_db
    restart: always
    environment:
      POSTGRES_DB: tinder_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    container_name: redis_tinder
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data:



